package com.sportspeople.main.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import com.sportspeople.main.models.Country;
import com.sportspeople.main.service.CountryService;

import jakarta.validation.Valid;

@Controller
@RequestMapping(path = "/countries")
public class CountryController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private CountryService countryService;

    @GetMapping("/all")
    public @ResponseBody Iterable<Country> getAllCountries() {
        return countryService.getAllCountries();
    }

    @PostMapping(path = "/add")
    public @ResponseBody ResponseEntity<Country> addNewCountry(@Valid @RequestBody Country country) {
        return ResponseEntity.ok(countryService.saveCountry(country));
    }
}